config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/abinit/abinit:
      branch: master
      repo: https://github.com/abinit/abinit
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/abinit/abinit git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-platinum-mist.sh
        container: qc.acc_gimpy-bronze-goose
  QC.Doc:
    repos:
      github.com/abinit/abinit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-violet-hummingbird.sh
        container: qc.doc_woolly-razzmatazz-dragonfly
      github.com/abinit/abinit git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cream-bobcat.sh
        container: qc.doc_crabby-heliotrope-camel
      github.com/abinit/abinit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-wheat-kiwi.sh
        container: qc.doc_muggy-auburn-goat
      github.com/abinit/abinit restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-tan-spitz.sh
        container: qc.doc_pretty-tomato-fly
  QC.Lic:
    repos:
      github.com/abinit/abinit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lilac-mist.sh
        container: qc.lic_cheeky-persimmon-bracke
  QC.Sec:
    repos:
      github.com/abinit/abinit bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ecru-spitz.sh
        container: qc.sec_muzzy-celadon-walrus
  QC.Sty:
    repos:
      github.com/abinit/abinit flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-jade-dogfish.sh
        container: qc.sty_bumpy-rose-salamander
      github.com/abinit/abinit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ochre-moose.sh
        container: qc.sty_smelly-ruby-akbash
  QC.Ver:
    repos:
      github.com/abinit/abinit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amethyst-civet.sh
        container: qc.ver_muggy-champagne-beetle
timeout: 1800
